// constants/documentModels.ts
export const DOCUMENT_MODELS = {
  AUTO_DECLARACAO: {
    title: "Auto de Declarações",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Nº da Folha",
        type: "text",
        placeholder: "Ex: 1",
        value: "",
      },
      {
        name: "label",
        label: "Título do Documento",
        type: "text",
        placeholder: "Ex: AUTO DE DECLARAÇÕES",
        value: "AUTO DE DECLARAÇÕES",
      },
      {
        name: "tipoDeclaracao",
        label: "Tipo de Declaração",
        type: "text",
        placeholder: "Ex: Inicial, Aditamento",
        value: "INICIAL",
      },
      {
        name: "dataEmissao",
        label: "Data de Emissão",
        type: "date",
        placeholder: "",
        value: "",
      },
      {
        name: "enderecoCidade",
        label: "Cidade",
        type: "text",
        placeholder: "Ex: Luanda",
        value: "",
      },
      {
        name: "descricaoOndeSeAchava",
        label: "Onde se achava",
        type: "text",
        placeholder: "Ex: No piquete da DPIC",
        value: "",
      },
      {
        name: "declarante",
        label: "Nome do Declarante",
        type: "text",
        placeholder: "Nome completo",
        value: "",
      },
      {
        name: "declarantePai",
        label: "Filiação (Pai)",
        type: "text",
        placeholder: "",
        value: "",
      },
      {
        name: "declaranteMae",
        label: "Filiação (Mãe)",
        type: "text",
        placeholder: "",
        value: "",
      },
      {
        name: "declaranteEstadoCivil",
        label: "Estado Civil",
        type: "select",
        options: [
          { value: "SOLTEIRO", label: "Solteiro(a)" },
          { value: "CASADO", label: "Casado(a)" },
          { value: "DIVORCIADO", label: "Divorciado(a)" },
          { value: "VIUVO", label: "Viúvo(a)" },
        ],
        value: "",
      },
      {
        name: "declaranteDataNascimento",
        label: "Data de Nascimento",
        type: "date",
        value: "",
      },
      {
        name: "declaranteNaturalidade",
        label: "Naturalidade",
        type: "text",
        placeholder: "Província/Município",
        value: "",
      },
      {
        name: "declaranteProfissao",
        label: "Profissão",
        type: "text",
        placeholder: "",
        value: "",
      },
      {
        name: "declaranteBI",
        label: "Número do B.I.",
        type: "text",
        placeholder: "Número do Bilhete de Identidade",
        value: "",
      },
      {
        name: "declaranteBIEmissao",
        label: "Data de Emissão do B.I.",
        type: "date",
        value: "",
      },
      {
        name: "declaranteBILocal",
        label: "Local de Emissão do B.I.",
        type: "text",
        placeholder: "Ex: Luanda",
        value: "",
      },
      {
        name: "declaranteEmail",
        label: "E-mail",
        type: "email",
        placeholder: "exemplo@dominio.com",
        value: "",
      },
      {
        name: "declaranteTelefone",
        label: "Telefone",
        type: "tel",
        placeholder: "Ex: 9xx xxx xxx",
        value: "",
      },
      {
        name: "declaranteProvincia",
        label: "Província de Residência",
        type: "text",
        value: "",
      },
      {
        name: "declaranteMunicipio",
        label: "Município de Residência",
        type: "text",
        value: "",
      },
      {
        name: "declaranteBairro",
        label: "Bairro",
        type: "text",
        value: "",
      },
      {
        name: "declaranteRua",
        label: "Rua",
        type: "text",
        value: "",
      },
      {
        name: "declaranteCasaNumero",
        label: "Nº da Casa",
        type: "text",
        value: "",
      },
      {
        name: "materiaAutos",
        label: "Matéria dos Autos",
        type: "textarea",
        placeholder: "Relato detalhado das declarações...",
        value: "",
      },
    ],
  },
  AUTO_DECLARACAO_EM_ADITAMENTO: {
    title: "Auto de Declarações em Aditamento",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Nº da Folha",
        type: "text",
        placeholder: "Ex: 1",
        value: "",
      },
      {
        name: "label",
        label: "Título do Documento",
        type: "text",
        placeholder: "Ex: AUTO DE DECLARAÇÕES",
        value: "AUTO DE DECLARAÇÕES",
      },
      {
        name: "tipoDeclaracao",
        label: "Tipo de Declaração",
        type: "text",
        placeholder: "Ex: Inicial, Aditamento",
        value: "INICIAL",
      },
      {
        name: "dataEmissao",
        label: "Data de Emissão",
        type: "date",
        placeholder: "",
        value: "",
      },
      {
        name: "enderecoCidade",
        label: "Cidade",
        type: "text",
        placeholder: "Ex: Luanda",
        value: "",
      },
      {
        name: "descricaoOndeSeAchava",
        label: "Onde se achava",
        type: "text",
        placeholder: "Ex: No piquete da DPIC",
        value: "",
      },
      {
        name: "declarante",
        label: "Nome do Declarante",
        type: "text",
        placeholder: "Nome completo",
        value: "",
      },
      {
        name: "declarantePai",
        label: "Filiação (Pai)",
        type: "text",
        placeholder: "",
        value: "",
      },
      {
        name: "declaranteMae",
        label: "Filiação (Mãe)",
        type: "text",
        placeholder: "",
        value: "",
      },
      {
        name: "declaranteEstadoCivil",
        label: "Estado Civil",
        type: "select",
        options: [
          { value: "SOLTEIRO", label: "Solteiro(a)" },
          { value: "CASADO", label: "Casado(a)" },
          { value: "DIVORCIADO", label: "Divorciado(a)" },
          { value: "VIUVO", label: "Viúvo(a)" },
        ],
        value: "",
      },
      {
        name: "declaranteDataNascimento",
        label: "Data de Nascimento",
        type: "date",
        value: "",
      },
      {
        name: "declaranteNaturalidade",
        label: "Naturalidade",
        type: "text",
        placeholder: "Província/Município",
        value: "",
      },
      {
        name: "declaranteProfissao",
        label: "Profissão",
        type: "text",
        placeholder: "",
        value: "",
      },
      {
        name: "declaranteBI",
        label: "Número do B.I.",
        type: "text",
        placeholder: "Número do Bilhete de Identidade",
        value: "",
      },
      {
        name: "declaranteBIEmissao",
        label: "Data de Emissão do B.I.",
        type: "date",
        value: "",
      },
      {
        name: "declaranteBILocal",
        label: "Local de Emissão do B.I.",
        type: "text",
        placeholder: "Ex: Luanda",
        value: "",
      },
      {
        name: "declaranteEmail",
        label: "E-mail",
        type: "email",
        placeholder: "exemplo@dominio.com",
        value: "",
      },
      {
        name: "declaranteTelefone",
        label: "Telefone",
        type: "tel",
        placeholder: "Ex: 9xx xxx xxx",
        value: "",
      },
      {
        name: "declaranteProvincia",
        label: "Província de Residência",
        type: "text",
        value: "",
      },
      {
        name: "declaranteMunicipio",
        label: "Município de Residência",
        type: "text",
        value: "",
      },
      {
        name: "declaranteBairro",
        label: "Bairro",
        type: "text",
        value: "",
      },
      {
        name: "declaranteRua",
        label: "Rua",
        type: "text",
        value: "",
      },
      {
        name: "declaranteCasaNumero",
        label: "Nº da Casa",
        type: "text",
        value: "",
      },
      {
        name: "materiaAutos",
        label: "Matéria dos Autos",
        type: "textarea",
        placeholder: "Relato detalhado das declarações...",
        value: "",
      },
    ],
  },
  AUTO_DEPOIMENTO_DIRECTO: {
    title: "Auto de Depoimento Directo",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Nº da Folha",
        type: "text",
        placeholder: "Ex: 1",
        value: "",
      },
      {
        name: "label",
        label: "Título do Documento",
        type: "text",
        placeholder: "Ex: AUTO DE DEPOIMENTO DIRECTO",
        value: "AUTO DE DEPOIMENTO DIRECTO",
      },
      {
        name: "dataEmissao",
        label: "Data de Emissão",
        type: "date",
        value: "",
      },
      {
        name: "enderecoCidade",
        label: "Cidade",
        type: "text",
        placeholder: "Ex: Luanda",
        value: "",
      },
      {
        name: "descricaoOndeSeAchava",
        label: "Local da Diligência",
        type: "text",
        placeholder: "Ex: Nas instalações da DTTI",
        value: "",
      },
      {
        name: "testemunhaNome",
        label: "Nome da Testemunha",
        type: "text",
        placeholder: "Nome completo",
        value: "",
      },
      {
        name: "testemunhaPai",
        label: "Nome do Pai",
        type: "text",
        placeholder: "",
        value: "",
      },
      {
        name: "testemunhaMae",
        label: "Nome da Mãe",
        type: "text",
        placeholder: "",
        value: "",
      },
      {
        name: "testemunhaEstadoCivil",
        label: "Estado Civil",
        type: "select",
        options: [
          { value: "SOLTEIRO", label: "Solteiro(a)" },
          { value: "CASADO", label: "Casado(a)" },
          { value: "DIVORCIADO", label: "Divorciado(a)" },
          { value: "VIUVO", label: "Viúvo(a)" },
        ],
        value: "",
      },
      {
        name: "testemunhaDataNascimento",
        label: "Data de Nascimento",
        type: "date",
        value: "",
      },
      {
        name: "testemunhaNaturalidade",
        label: "Naturalidade",
        type: "text",
        placeholder: "Ex: Luanda, Sambizanga",
        value: "",
      },
      {
        name: "testemunhaProfissao",
        label: "Profissão",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaBI",
        label: "B.I. / Passaporte",
        type: "text",
        placeholder: "Número do documento",
        value: "",
      },
      {
        name: "testemunhaBIEmissao",
        label: "Data de Emissão (Documento)",
        type: "date",
        value: "",
      },
      {
        name: "testemunhaBILocal",
        label: "Local de Emissão (Documento)",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaEmail",
        label: "E-mail",
        type: "email",
        value: "",
      },
      {
        name: "testemunhaTelefone",
        label: "Telefone",
        type: "tel",
        value: "",
      },
      {
        name: "testemunhaProvincia",
        label: "Província",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaMunicipio",
        label: "Município",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaBairro",
        label: "Bairro",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaRua",
        label: "Rua",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaCasaNumero",
        label: "Nº da Casa",
        type: "text",
        value: "",
      },
      {
        name: "relacoesParentesco",
        label: "Relações de Parentesco",
        type: "text",
        placeholder: "Ex: Sem relações de parentesco com o arguido",
        value: "",
      },
      {
        name: "depoimentoConteudo",
        label: "Conteúdo do Depoimento",
        type: "textarea",
        placeholder: "Relato detalhado dos factos presenciados...",
        value: "",
      },
    ],
  },
  AUTO_DILIGENCIA: {
    title: "Auto de Diligências",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "label",
        label: "Título do Documento",
        type: "text",
        placeholder: "Ex: AUTO DE DILIGÊNCIA",
        value: "AUTO DE DILIGÊNCIA",
      },
      {
        name: "direccaoCentral",
        label: "Direcção Central / Unidade",
        type: "text",
        placeholder: "Ex: Direcção Central de Combate aos Crimes...",
        value: "",
      },
      {
        name: "dataExtenso",
        label: "Data por Extenso",
        type: "text",
        placeholder: "Ex: Aos vinte e um dias do mês de Abril...",
        value: "",
      },
      {
        name: "cidade",
        label: "Cidade",
        type: "text",
        placeholder: "Ex: Luanda",
        value: "Luanda",
      },
      {
        name: "unidadeSIC",
        label: "Unidade do SIC",
        type: "text",
        placeholder: "Ex: Departamento de Crimes Contra o Património",
        value: "",
      },
      {
        name: "horaInicio",
        label: "Hora de Início",
        type: "time",
        value: "",
      },
      {
        name: "investigadorNome",
        label: "Investigador Responsável",
        type: "text",
        placeholder: "Nome do investigador",
        value: "",
      },
      {
        name: "acompanhanteNome",
        label: "Acompanhante/Equipa",
        type: "text",
        placeholder: "Nome do agente acompanhante",
        value: "",
      },
      {
        name: "localDestino",
        label: "Local do Destino",
        type: "text",
        placeholder: "Distrito, Bairro, Rua ou Coordenadas",
        value: "",
      },
      {
        name: "objetivoDiligencia",
        label: "Objectivo da Diligência",
        type: "textarea",
        placeholder:
          "Descreva o propósito da missão (ex: busca, captura, verificação)",
        value: "",
      },
      {
        name: "desenvolvimentoTexto",
        label: "Desenvolvimento da Diligência",
        type: "textarea",
        placeholder: "Relato detalhado das acções efectuadas no local...",
        value: "",
      },
      {
        name: "resultadoDiligencia",
        label: "Resultado",
        type: "select",
        options: [
          { value: "FRUTÍFERO", label: "Frutífero" },
          { value: "INFRUTÍFERO", label: "Infrutífero" },
          { value: "PARCIALMENTE FRUTÍFERO", label: "Parcialmente Frutífero" },
        ],
        value: "",
      },
      {
        name: "horaFim",
        label: "Hora de Término",
        type: "time",
        value: "",
      },
      {
        name: "conclusaoTexto",
        label: "Conclusão",
        type: "textarea",
        placeholder: "Considerações finais ou providências tomadas",
        value: "",
      },
    ],
  },
  AUTO_QUEIXA: {
    title: "Auto de Queixa",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data de Emissão",
        type: "date",
        value: "",
      },
      {
        name: "horaEmissao",
        label: "Hora da Ocorrência/Registo",
        type: "time",
        value: "",
      },
      {
        name: "investigadorNome",
        label: "Investigador / Instrutor",
        type: "text",
        placeholder: "Nome do oficial que lavra o auto",
        value: "",
      },
      {
        name: "unidadeSIC",
        label: "Unidade do SIC",
        type: "text",
        placeholder: "Ex: Esquadra de Polícia / Direcção Central",
        value: "",
      },
      {
        name: "queixosoDados",
        label: "Dados do Queixoso",
        type: "textarea",
        placeholder:
          "Identificação completa: Nome, filiação, naturalidade, estado civil, BI, residência e contacto.",
        value: "",
      },
      {
        name: "contraQuem",
        label: "Contra Quem (Acusado)",
        type: "text",
        placeholder: "Nome ou 'Desconhecidos'",
        value: "",
      },
      {
        name: "acusacaoMotivo",
        label: "Descrição dos Factos (Acusação)",
        type: "textarea",
        placeholder: "Descreva detalhadamente o que aconteceu, onde e como.",
        value: "",
      },
      {
        name: "testemunhas",
        label: "Testemunhas",
        type: "textarea",
        placeholder: "Nome e contacto de possíveis testemunhas",
        value: "",
      },
      {
        name: "desejaProcedimento",
        label: "Deseja procedimento criminal?",
        type: "checkbox", // Ou 'select' se preferir Sim/Não
        value: true,
      },
    ],
  },
  AUTO_CONSTITUICAO_DE_ARGUIDO: {
    title: "Auto de Constituição de Arguido",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 05",
        value: "",
      },
      {
        name: "label",
        label: "Título do Documento",
        type: "text",
        placeholder: "Ex: AUTO DE CONSTITUIÇÃO DE ARGUIDO",
        value: "AUTO DE CONSTITUIÇÃO DE ARGUIDO",
      },
      {
        name: "dataEmissao",
        label: "Data de Emissão",
        type: "date",
        value: "",
      },
      {
        name: "enderecoCidade",
        label: "Cidade/Localidade",
        type: "text",
        placeholder: "Ex: Luanda",
        value: "Luanda",
      },
      {
        name: "descricaoOndeSeAchava",
        label: "Local (Onde se achava)",
        type: "text",
        placeholder: "Ex: No edifício da Direcção Central...",
        value: "",
      },
      {
        name: "arguidoNome",
        label: "Nome do Arguido",
        type: "text",
        placeholder: "Nome completo do constituído",
        value: "",
      },
      {
        name: "crimeTipificacao",
        label: "Tipificação do Crime",
        type: "textarea",
        placeholder: "Descreva os factos constitutivos e o enquadramento legal",
        value: "",
      },
      {
        name: "advogadoDefensor",
        label: "Advogado / Defensor",
        type: "text",
        placeholder: "Nome do Advogado ou Defensor Público",
        value: "",
      },
    ],
  },
  AUTO_INTERROGATORIO: {
    title: "Auto de Interrogatório",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 10",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data do Interrogatório",
        type: "date",
        value: "",
      },
      {
        name: "enderecoCidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "descricaoOndeSeAchava",
        label: "Local da Diligência",
        type: "text",
        placeholder: "Ex: Nas instalações do SIC...",
        value: "",
      },
      {
        name: "defensorNome",
        label: "Nome do Defensor/Advogado",
        type: "text",
        placeholder: "Nome completo",
        value: "",
      },
      {
        name: "arguidoNome",
        label: "Nome do Arguido",
        type: "text",
        placeholder: "Nome completo",
        value: "",
      },
      {
        name: "arguidoPai",
        label: "Nome do Pai",
        type: "text",
        value: "",
      },
      {
        name: "arguidoMae",
        label: "Nome da Mãe",
        type: "text",
        value: "",
      },
      {
        name: "arguidoEstadoCivil",
        label: "Estado Civil",
        type: "select",
        options: [
          { value: "SOLTEIRO", label: "Solteiro(a)" },
          { value: "CASADO", label: "Casado(a)" },
          { value: "DIVORCIADO", label: "Divorciado(a)" },
          { value: "VIÚVO", label: "Viúvo(a)" },
          { value: "UNIÃO DE FACTO", label: "União de Facto" },
        ],
        value: "",
      },
      {
        name: "arguidoDataNascimento",
        label: "Data de Nascimento",
        type: "date",
        value: "",
      },
      {
        name: "arguidoNaturalidade",
        label: "Naturalidade (Província/País)",
        type: "text",
        value: "",
      },
      {
        name: "arguidoProfissao",
        label: "Profissão/Ocupação",
        type: "text",
        value: "",
      },
      {
        name: "arguidoBI",
        label: "Nº do B.I. / Passaporte",
        type: "text",
        value: "",
      },
      {
        name: "arguidoBIEmissao",
        label: "Data de Emissão do B.I.",
        type: "date",
        value: "",
      },
      {
        name: "arguidoBILocal",
        label: "Local de Emissão do B.I.",
        type: "text",
        value: "",
      },
      {
        name: "arguidoEmail",
        label: "E-mail",
        type: "email",
        value: "",
      },
      {
        name: "arguidoTelefone",
        label: "Telefone de Contacto",
        type: "tel",
        value: "",
      },
      {
        name: "arguidoProvincia",
        label: "Província de Residência",
        type: "text",
        value: "Luanda",
      },
      {
        name: "arguidoMunicipio",
        label: "Município",
        type: "text",
        value: "",
      },
      {
        name: "arguidoBairro",
        label: "Bairro",
        type: "text",
        value: "",
      },
      {
        name: "arguidoRua",
        label: "Rua",
        type: "text",
        value: "",
      },
      {
        name: "arguidoCasaNumero",
        label: "Nº da Casa",
        type: "text",
        value: "",
      },
      {
        name: "antecedentesCriminais",
        label: "Antecedentes Criminais",
        type: "textarea",
        placeholder: "Já esteve preso? Se sim, onde e por quanto tempo?",
        value: "",
      },
      {
        name: "materiaAutosResposta",
        label: "Matéria dos Autos (Depoimento)",
        type: "textarea",
        placeholder: "Relato do arguido sobre os factos de que é acusado...",
        value: "",
      },
    ],
  },
  AUTO_RECONHECIMENTO_FISICO_E_DIRECTO_DE_OBJS: {
    title: "Auto de Reconhecimento Físico e Directo de Objecto",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 18",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data do Reconhecimento",
        type: "date",
        value: "",
      },
      {
        name: "cidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "unidadeSIC",
        label: "Unidade do SIC",
        type: "text",
        placeholder: "Ex: Direcção Central de Combate ao Roubo de Viaturas",
        value: "",
      },
      {
        name: "investigadorNome",
        label: "Investigador / Instrutor",
        type: "text",
        placeholder: "Nome do oficial responsável",
        value: "",
      },
      {
        name: "identificadorNome",
        label: "Nome do Reconhecente",
        type: "text",
        placeholder: "Pessoa que fará a identificação",
        value: "",
      },
      {
        name: "descricaoPreviaObjecto",
        label: "Descrição Prévia do Objecto",
        type: "textarea",
        placeholder:
          "Características mencionadas ANTES da exibição (cor, marcas, defeitos...)",
        value: "",
      },
      {
        name: "justificativaConhecimento",
        label: "Razão do Conhecimento",
        type: "textarea",
        placeholder:
          "Como a pessoa conhece o objecto e como reteve as características?",
        value: "",
      },
      {
        name: "numeroSinalizacao",
        label: "Número no Alinhamento",
        type: "text",
        placeholder: "Nº de ordem atribuído ao objecto entre os demais",
        value: "",
      },
      {
        name: "resultadoReconhecimento",
        label: "Resultado Final",
        type: "select",
        options: [
          { value: "POSITIVO", label: "Reconheceu sem dúvidas" },
          { value: "NEGATIVO", label: "Não reconheceu" },
          { value: "POSITIVO_COM_RESERVAS", label: "Reconheceu com reservas" },
        ],
        value: "",
      },
    ],
  },
  AUTO_RECONHECIMENTO_FISICO_E_DIRECTO_DE_PESSOAS: {
    title: "Auto de Reconhecimento Físico e Directo de Pessoas",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 20",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data do Reconhecimento",
        type: "date",
        value: "",
      },
      {
        name: "cidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "unidadeSIC",
        label: "Unidade/Local do SIC",
        type: "text",
        placeholder: "Ex: Direcção Central de Combate ao Crime Organizado",
        value: "",
      },
      {
        name: "investigadorNome",
        label: "Investigador / Instrutor",
        type: "text",
        placeholder: "Nome do oficial responsável",
        value: "",
      },
      {
        name: "identificadorNome",
        label: "Nome do Reconhecente",
        type: "text",
        placeholder: "Vítima ou Testemunha",
        value: "",
      },
      {
        name: "descricaoPreviaPessoa",
        label: "Descrição Física Prévia",
        type: "textarea",
        placeholder:
          "Altura, cor da pele, vestuário, sinais particulares descritos ANTES de ver os suspeitos",
        value: "",
      },
      {
        name: "justificativaConhecimento",
        label: "Razão do Conhecimento",
        type: "textarea",
        placeholder:
          "Como a pessoa conhece o suspeito ou em que circunstâncias o viu?",
        value: "",
      },
      {
        name: "posicoesPerfilamento",
        label: "Posições do Perfilamento",
        type: "textarea",
        placeholder:
          "Ex: 1. Suspeito (fulano); 2. Figurante (beltrano); 3. Figurante...",
        value: "",
      },
      {
        name: "resultadoReconhecimento",
        label: "Resultado do Reconhecimento",
        type: "select",
        options: [
          {
            value: "POSITIVO",
            label: "Reconheceu (Indique o número da posição)",
          },
          { value: "NEGATIVO", label: "Não reconheceu ninguém" },
          { value: "DUVIDOSO", label: "Apresentou dúvidas ou incertezas" },
        ],
        value: "",
      },
    ],
  },
  AUTO_DEPOIMENTO_INDIRECTO: {
    title: "Auto de Depoimento Indirecto",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 25",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data do Depoimento",
        type: "date",
        value: "",
      },
      {
        name: "enderecoCidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "descricaoOndeSeAchava",
        label: "Local da Diligência",
        type: "text",
        placeholder: "Ex: Nas instalações do SIC...",
        value: "",
      },
      {
        name: "testemunhaNome",
        label: "Nome da Testemunha",
        type: "text",
        placeholder: "Nome completo",
        value: "",
      },
      {
        name: "testemunhaPai",
        label: "Nome do Pai",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaMae",
        label: "Nome da Mãe",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaEstadoCivil",
        label: "Estado Civil",
        type: "select",
        options: [
          { value: "SOLTEIRO", label: "Solteiro(a)" },
          { value: "CASADO", label: "Casado(a)" },
          { value: "DIVORCIADO", label: "Divorciado(a)" },
          { value: "VIÚVO", label: "Viúvo(a)" },
          { value: "UNIÃO DE FACTO", label: "União de Facto" },
        ],
        value: "",
      },
      {
        name: "testemunhaDataNascimento",
        label: "Data de Nascimento",
        type: "date",
        value: "",
      },
      {
        name: "testemunhaNaturalidade",
        label: "Naturalidade",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaProfissao",
        label: "Profissão",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaBI",
        label: "Nº do B.I. / Passaporte",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaBIEmissao",
        label: "Data de Emissão do B.I.",
        type: "date",
        value: "",
      },
      {
        name: "testemunhaBILocal",
        label: "Local de Emissão do B.I.",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaEmail",
        label: "E-mail",
        type: "email",
        value: "",
      },
      {
        name: "testemunhaTelefone",
        label: "Telefone",
        type: "tel",
        value: "",
      },
      {
        name: "testemunhaProvincia",
        label: "Província",
        type: "text",
        value: "Luanda",
      },
      {
        name: "testemunhaMunicipio",
        label: "Município",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaBairro",
        label: "Bairro",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaRua",
        label: "Rua",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaCasaNumero",
        label: "Nº da Casa",
        type: "text",
        value: "",
      },
      {
        name: "relacoesParentesco",
        label: "Relações de Parentesco",
        type: "text",
        placeholder: "Ex: Primo do arguido / Sem parentesco",
        value: "Nenhuma",
      },
      {
        name: "depoimentoConteudo",
        label: "Conteúdo do Depoimento",
        type: "textarea",
        placeholder:
          "Relato detalhado do que a testemunha ouviu dizer, mencionando a fonte da informação...",
        value: "",
      },
    ],
  },
  AUTO_EXAME_DIRECTO: {
    title: "Auto de Exame Directo",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 30",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data do Exame",
        type: "date",
        value: "",
      },
      {
        name: "cidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "unidadeSIC",
        label: "Unidade do SIC",
        type: "text",
        placeholder: "Ex: Laboratório de Criminalística / Direcção Central",
        value: "",
      },
      {
        name: "investigadorNome",
        label: "Investigador / Instrutor",
        type: "text",
        placeholder: "Nome do oficial que preside o ato",
        value: "",
      },
      {
        name: "peritosNomes",
        label: "Peritos Notificados",
        type: "textarea",
        placeholder: "Nome(s) e especialidade(s) dos peritos ou médicos",
        value: "",
      },
      {
        name: "objectoExame",
        label: "Objecto do Exame",
        type: "textarea",
        placeholder:
          "Descreva o que será examinado (Ex: Cadáver, Arma de Fogo, Veículo acidentado...)",
        value: "",
      },
      {
        name: "conclusoesExame",
        label: "Conclusões do Exame",
        type: "textarea",
        placeholder:
          "Relato técnico dos peritos sobre os vestígios encontrados e parecer final",
        value: "",
      },
    ],
  },
  AUTO_EXAME_DIRECTO_E_AVALIACAO: {
    title: "Auto de Exame Directo e Avaliação",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 35",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data da Avaliação",
        type: "date",
        value: "",
      },
      {
        name: "cidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "unidadeSIC",
        label: "Unidade do SIC",
        type: "text",
        placeholder: "Ex: Departamento de Crimes Contra o Património",
        value: "",
      },
      {
        name: "investigadorNome",
        label: "Investigador / Instrutor",
        type: "text",
        placeholder: "Nome do oficial presidente",
        value: "",
      },
      {
        name: "peritosNomes",
        label: "Peritos (Especialistas ou Louvados)",
        type: "textarea",
        placeholder: "Nome dos especialistas que realizarão a avaliação",
        value: "",
      },
      {
        name: "objectoAvaliacao",
        label: "Objecto da Avaliação",
        type: "textarea",
        placeholder:
          "Descreva o bem (Ex: Telemóvel marca X, Computador, Joias, etc.)",
        value: "",
      },
      {
        name: "resultadoExameAvaliacao",
        label: "Resultado e Valor Atribuído",
        type: "textarea",
        placeholder:
          "Descrição técnica do estado do bem e o valor estimado em Kwanza (AKZ)",
        value: "",
      },
    ],
  },
  AUTO_RECONSTITUICAO: {
    title: "Auto de Reconstituição",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 45",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data da Reconstituição",
        type: "date",
        value: "",
      },
      {
        name: "horaInicioTermino",
        label: "Horário (Início e Término)",
        type: "text",
        placeholder: "Ex: Das 09:00h às 11:30h",
        value: "",
      },
      {
        name: "cidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "unidadeSIC",
        label: "Unidade do SIC",
        type: "text",
        placeholder:
          "Ex: Direcção Central de Combate aos Crimes Contra as Pessoas",
        value: "",
      },
      {
        name: "investigadorNome",
        label: "Investigador / Instrutor",
        type: "text",
        placeholder: "Nome do oficial que preside o ato",
        value: "",
      },
      {
        name: "peritosNomes",
        label: "Peritos (Compromissados)",
        type: "textarea",
        placeholder:
          "Nomes dos peritos que prestaram juramento/compromisso de honra",
        value: "",
      },
      {
        name: "intervenientesNomes",
        label: "Intervenientes Presentes",
        type: "textarea",
        placeholder:
          "Arguidos, vítimas, testemunhas e advogados presentes na diligência",
        value: "",
      },
      {
        name: "descricaoReconstituicao",
        label: "Relato da Reconstituição",
        type: "textarea",
        placeholder:
          "Descrição passo a passo da movimentação dos intervenientes e da dinâmica dos factos...",
        value: "",
      },
    ],
  },
  AUTO_CORPO_DE_DELITO_INDIRETO: {
    title: "Auto de Delito Indirecto",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 50",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data do Depoimento",
        type: "date",
        value: "",
      },
      {
        name: "cidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "unidadeSIC",
        label: "Unidade do SIC",
        type: "text",
        placeholder: "Ex: Departamento de Crimes Contra a Ordem Pública",
        value: "",
      },
      {
        name: "chefeDepartamento",
        label: "Chefe do Departamento / Superior",
        type: "text",
        placeholder: "Nome e Categoria (Ex: Superintendente Chefe Fulano)",
        value: "",
      },
      {
        name: "investigadorNome",
        label: "Investigador / Instrutor",
        type: "text",
        placeholder: "Oficial que colhe as declarações",
        value: "",
      },
      {
        name: "testemunhaNome",
        label: "Nome da Testemunha",
        type: "text",
        placeholder: "Nome completo",
        value: "",
      },
      {
        name: "testemunhaIdade",
        label: "Idade",
        type: "number",
        value: "",
      },
      {
        name: "testemunhaDataNascimento",
        label: "Data de Nascimento",
        type: "date",
        value: "",
      },
      {
        name: "testemunhaEstadoCivil",
        label: "Estado Civil",
        type: "select",
        options: [
          { value: "SOLTEIRO", label: "Solteiro(a)" },
          { value: "CASADO", label: "Casado(a)" },
          { value: "DIVORCIADO", label: "Divorciado(a)" },
          { value: "VIÚVO", label: "Viúvo(a)" },
          { value: "UNIÃO DE FACTO", label: "União de Facto" },
        ],
        value: "",
      },
      {
        name: "testemunhaProfissao",
        label: "Profissão",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaPai",
        label: "Nome do Pai",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaMae",
        label: "Nome da Mãe",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaNaturalidade",
        label: "Naturalidade",
        type: "text",
        value: "",
      },
      {
        name: "testemunhaEndereco",
        label: "Endereço Completo (Residência)",
        type: "textarea",
        placeholder: "Província, Município, Bairro, Rua e Casa",
        value: "",
      },
      {
        name: "testemunhaTelefone",
        label: "Telefone de Contacto",
        type: "tel",
        value: "",
      },
      {
        name: "depoimentoConteudo",
        label: "Conteúdo das Declarações",
        type: "textarea",
        placeholder:
          "Relato fiel e detalhado do que a testemunha presenciou ou sabe sobre os factos...",
        value: "",
      },
    ],
  },
  AUTO_ACARECACAO: {
    title: "Auto de Delito Indirecto",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "numeroFolha",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 60",
        value: "",
      },
      {
        name: "dataEmissao",
        label: "Data da Acareação",
        type: "date",
        value: "",
      },
      {
        name: "cidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "unidadeSIC",
        label: "Unidade do SIC",
        type: "text",
        placeholder: "Ex: Direcção Central de Combate ao Narcotráfico",
        value: "",
      },
      {
        name: "investigadorNome",
        label: "Investigador / Instrutor",
        type: "text",
        placeholder: "Nome do oficial que preside o confronto",
        value: "",
      },
      {
        name: "acareadosNomes",
        label: "Intervenientes Acareados",
        type: "textarea",
        placeholder: "Ex: Arguido [Nome] e Testemunha [Nome]",
        value: "",
      },
      {
        name: "outrosPresentes",
        label: "Outros Presentes",
        type: "textarea",
        placeholder:
          "Advogados, Defensores, Curadores ou Oficiais de diligência",
        value: "",
      },
      {
        name: "conteudoAcareacao",
        label: "Conteúdo da Acareação",
        type: "textarea",
        placeholder:
          "Relato das perguntas feitas sobre as contradições e as reações/respostas de cada acareado...",
        value: "",
      },
    ],
  },
  CAPA_PROCESSO: {
    title: "Capa de Processo Crime",
    fields: [
      {
        name: "anoProcesso",
        label: "Ano do Processo",
        type: "text",
        placeholder: "Ex: 2026",
        value: "2026",
      },
      {
        name: "processoNumeroPGR",
        label: "Nº de Processo (PGR)",
        type: "text",
        placeholder: "Ex: PGR/123/2026",
        value: "",
      },
      {
        name: "expedienteNumeroSIC",
        label: "Nº de Expediente (SIC)",
        type: "text",
        placeholder: "Ex: 456/2026-DP",
        value: "",
      },
      {
        name: "magistradoMP",
        label: "Magistrado do Ministério Público",
        type: "text",
        placeholder: "Nome do Procurador responsável",
        value: "",
      },
      {
        name: "instrutorProcessual",
        label: "Instrutor do Processo",
        type: "text",
        placeholder: "Nome do oficial do SIC",
        value: "",
      },
      {
        name: "crimeSuspeita",
        label: "Crime em Suspeita",
        type: "text",
        placeholder: "Ex: Roubo Qualificado, Homicídio...",
        value: "",
      },
      {
        name: "queixosoOfendido",
        label: "Queixoso / Ofendido",
        type: "text",
        placeholder: "Nome do queixoso",
        value: "",
      },
      {
        name: "arguidoNome",
        label: "Arguido(s)",
        type: "text",
        placeholder: "Nome do(s) suspeito(s) ou 'Desconhecido'",
        value: "",
      },
      {
        name: "dataAutuacao",
        label: "Data de Autuação",
        type: "date",
        value: "",
      },
      {
        name: "cidadeAutuacao",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "escrivaoNome",
        label: "Escrivão / Oficial de Registo",
        type: "text",
        placeholder: "Nome de quem autua o processo",
        value: "",
      },
      {
        name: "livroNumero",
        label: "Livro Nº",
        type: "text",
        placeholder: "Ex: 01",
        value: "",
      },
      {
        name: "folhaNumero",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 01",
        value: "01",
      },
      {
        name: "seccaoRegisto",
        label: "Secção de Registo",
        type: "text",
        placeholder: "Ex: 1ª Secção de Crimes Comuns",
        value: "",
      },
    ],
  },
  CAPA_CARTA_PRECATORIA: {
    title: "Capa de Carta Precatória",
    fields: [
      {
        name: "anoCarta",
        label: "Ano da Carta",
        type: "text",
        placeholder: "Ex: 2026",
        value: "2026",
      },
      {
        name: "precaotoriaNumero",
        label: "Nº da Carta Precatória",
        type: "text",
        placeholder: "Ex: 045/2026",
        value: "",
      },
      {
        name: "processoOrigemPGR",
        label: "Nº do Processo de Origem",
        type: "text",
        placeholder: "Ex: PGR/789/2026-B",
        value: "",
      },
      {
        name: "entidadeDeprecante",
        label: "Entidade Deprecante (Solicitante)",
        type: "text",
        placeholder: "Ex: SIC - Benguela / PGR - Huambo",
        value: "",
      },
      {
        name: "instrutorProcessual",
        label: "Instrutor (Destinatário)",
        type: "text",
        placeholder: "Oficial que cumprirá a diligência",
        value: "",
      },
      {
        name: "crimeReferencia",
        label: "Crime de Referência",
        type: "text",
        placeholder: "Ex: Abuso de Confiança, Burla...",
        value: "",
      },
      {
        name: "dataAutuacao",
        label: "Data de Autuação (Recebimento)",
        type: "date",
        value: "",
      },
      {
        name: "cidadeAutuacao",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "escrivaoNome",
        label: "Escrivão / Oficial de Registo",
        type: "text",
        placeholder: "Nome de quem autua a precatória",
        value: "",
      },
      {
        name: "livroNumero",
        label: "Livro de Registo Nº",
        type: "text",
        placeholder: "Ex: 02",
        value: "",
      },
      {
        name: "folhaNumero",
        label: "Folha Nº",
        type: "text",
        placeholder: "Ex: 01",
        value: "01",
      },
      {
        name: "seccaoRegisto",
        label: "Secção de Registo",
        type: "text",
        placeholder: "Ex: Secção de Cartas Precatórias",
        value: "",
      },
    ],
  },
  COTA: {
    title: "Cota",
    fields: [
      {
        name: "processoNumero",
        label: "Número do Processo",
        type: "text",
        placeholder: "Ex: 123/2026",
        value: "",
      },
      {
        name: "dataCota",
        label: "Data da Juntada",
        type: "date",
        value: "",
      },
      {
        name: "cidade",
        label: "Cidade",
        type: "text",
        value: "Luanda",
      },
      {
        name: "nomeFornecedor",
        label: "Proveniência (Quem entregou)",
        type: "text",
        placeholder: "Ex: O queixoso, o arguido, uma instituição bancária",
        value: "",
      },
      {
        name: "descricaoDocumentos",
        label: "Descrição dos Documentos",
        type: "textarea",
        placeholder:
          "Ex: Dois recibos de pagamento, uma cópia do extrato bancário e três fotografias do local.",
        value: "",
      },
      {
        name: "contextoEntrega",
        label: "Contexto/Relevância",
        type: "textarea",
        placeholder:
          "Explique por que estes documentos estão a ser entregues e o que pretendem provar.",
        value: "",
      },
      {
        name: "instrutorNome",
        label: "Instrutor / Oficial Responsável",
        type: "text",
        placeholder: "Nome de quem recebe e junta os documentos",
        value: "",
      },
    ],
  },
  MANDADO_DE_DETENCAO: {
    title: "Mandado de Detenção",
  },
};
